# Generated by Django 2.1.15 on 2020-04-16 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='potangina',
        ),
    ]
